export const DOMAINS = [
  'Science',
  'Technology',
  'Mathematics',
  'Engineering',
  'Medicine & Health',
  'Environment & Nature',
  'Social Sciences',
  'Humanities',
  'Education & Learning',
  'Business & Economics',
  'Law & Governance',
  'Arts & Design',
  'Entertainment & Media',
  'Language & Communication',
  'Philosophy & Thought',
  'Travel & Geography',
  'Lifestyle & Society',
  'Sports & Games',
  'Politics & Current Affairs',
  'Space & Cosmology',
  'Religion & Spirituality',
  'Computing & Internet',
  'Data & AI',
  'Psychology & Mind',
  'Artisan & Crafts',
  'Culture & Society',
  'History & Civilization',
  'Finance & Investing',
  'Transportation',
  'Personal Development',
  'Education Tech & Research',
  'Food & Culinary',
  'Home & Living',
  'Fashion & Beauty',
  'Music',
  'Movies & TV',
  'Gaming',
  'Religion & Mythology',
  'Agriculture & Rural',
  'Metaphysics & Unknown'
];
